pipeline {
    agent any

    environment {
        DOCKERHUB_CREDENTIALS = credentials('dockerhub-credentials')
        GITHUB_CREDENTIALS = credentials('github-credentials')
    }

    stages {
        stage('Clone Repository') {
            steps {
                git credentialsId: 'github-credentials',
                    url: 'https://github.com/Lesego916/alx-backend-python.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                sh 'pip install -r requirements.txt || true'
            }
        }

        stage('Run Tests') {
            steps {
                sh 'pytest --junitxml=report.xml || true'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t lesego916/messaging_app:latest .'
            }
        }

        stage('Push Docker Image') {
            steps {
                sh '''
                docker login -u $DOCKERHUB_CREDENTIALS_USR -p $DOCKERHUB_CREDENTIALS_PSW
                docker push lesego916/messaging_app:latest
                '''
            }
        }
    }

    post {
        always {
            junit 'report.xml'
        }
    }
}
